pipeline {
    agent any
    tools {
        maven 'maven'
    }
    stages {
        stage('env') {
            steps {
                sh 'mvn --version'
            }
        }
        stage('build') {
            steps {
                dir("${GITHUB_WORKSPACE}/demo/java") {
                    sh 'mvn clean install -B --no-transfer-progress'
                }
            }
        }
    }
}