pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Hello World'
//                 script {
//                     for (d in DownloadService.Downloadable.all()) {
//                       println("${d.url} -> ${d.updateNow().kind}");
//                     }
//                 }
            }
            steps {
                dir("${GITHUB_WORKSPACE}/demo/javascript/my-react-app") {
                    nodejs(nodeJSInstallationName: 'NodeJS 18.3.0') {
                        sh 'npm ci'
                    }
                }
            }
        }
    }
}